// <auto-generated />
namespace MY_Ticari.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class kargotest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kargotest));
        
        string IMigrationMetadata.Id
        {
            get { return "202102071249368_kargotest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
